DROP TABLE IF EXISTS BASKET;
CREATE TABLE BASKET(
   ID   INT NOT NULL AUTO_INCREMENT,
   USER_ID     INT   ,
   BRAND_NAME  VARCHAR (100)   NOT NULL,
   CATEGORY VARCHAR (100)  NOT NULL,
   SIZE VARCHAR (100)     NOT NULL,
   QUANTITY VARCHAR (255) NOT NULL,
   ITEM_SUBTOTAL  VARCHAR (255)   NOT NULL,
   PRIMARY  KEY (ID) ,
   FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
   
);

INSERT INTO BASKET (USER_ID, BRAND_NAME ,CATEGORY, SIZE, QUANTITY, ITEM_SUBTOTAL)
VALUES (1,'CANADA GOOSE','Hybridge CW Element Jacket', '42', '1', '£3550');



