SELECT PRODUCTS.NAME,PRODUCTS.SIZE,PRODUCTS.BRAND, CATEGORIES.CATEGORY_TITLE, CATEGORIES.CATEGORY_SUB, CATEGORIES.CATEGORY_DESCRIPTION 
FROM PRODUCTS
INNER JOIN CATEGORIES ON PRODUCTS.CATEGORY_ID=CATEGORIES.ID
WHERE CATEGORIES.CATEGORY_SUB='TOPS' OR CATEGORIES.CATEGORY_SUB='Shirt';





