SELECT PRODUCTS.NAME,PRODUCTS.SIZE,PRODUCTS.BRAND, CATEGORIES.CATEGORY_TITLE, CATEGORIES.CATEGORY_SUB, CATEGORIES.CATEGORY_DESCRIPTION 
FROM PRODUCTS
INNER JOIN CATEGORIES ON PRODUCTS.CATEGORY_ID=CATEGORIES.ID
WHERE CATEGORIES.CATEGORY_SUB='Coffee Machine' AND CATEGORIES.ID= 1;

SELECT USERS.USER_NAME, USERS.FIRST_NAME, USERS.LAST_NAME, USERS.TEL, USERS.EMAIL, ORDERS.ID AS ORDER_ID, ORDERS.SHIPPING_DATE
FROM USERS
INNER JOIN ORDERS ON ORDERS.USER_ID=USERS.ID
WHERE USERS.ID= 1;


