DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE PRODUCTS(
   ID   INT              NOT NULL AUTO_INCREMENT,
   NAME VARCHAR (255)     NOT NULL,
   CATEGORY VARCHAR (100)  NOT NULL,
   SIZE VARCHAR (100)     NOT NULL,
   COLOUR varchar (20)   NOT NULL,
   QUANTITY varchar (100) NOT NULL,
   BRAND varchar (100)   NOT NULL,
    UUID varchar (255)   NOT NULL,
   PRIMARY KEY (ID)
   
);

INSERT INTO PRODUCTS (NAME,CATEGORY, SIZE, COLOUR, QUANTITY, BRAND, UUID)
VALUES ('Hybridge CW Element Jacket', 'Jacket', '42', 'BLACK', '1', 'CANADA GOOSE', 'bc7d650b-f778-4b8d-8f75-1bc1cd35a0b1');

INSERT INTO PRODUCTS (NAME,CATEGORY, SIZE, COLOUR, QUANTITY, BRAND, UUID)
VALUES ('Hybridge CW Element Jacket', 'Jacket', '46', 'GREEN', '1', 'CANADA GOOSE', '6efdbbd5-4937-4af8-a962-36fd9f59f8ea');








