INSERT INTO PRODUCTS (NAME,CATEGORY, SIZE, COLOUR, QUANTITY, BRAND, UUID)
VALUES ('Hybridge CW Element Jacket', 'Jacket', '42', 'BLACK', '1', 'CANADA GOOSE', 'bc7d650b-f778-4b8d-8f75-1bc1cd35a0b1');

INSERT INTO PRODUCTS (NAME,CATEGORY, SIZE, COLOUR, QUANTITY, BRAND, UUID)
VALUES ('Hybridge CW Element Jacket', 'Jacket', '46', 'GREEN', '1', 'CANADA GOOSE', 'bc7d650b-f778-4b8d-8f75-1bc1cd35a0b1');




INSERT INTO USER ( USER_NAME, FIRST_NAME, SURNAME, PASSWORD)
VALUES ('Ali007','Ali', 'Varzandeh','007');

INSERT INTO USER ( USER_NAME, FIRST_NAME, SURNAME, PASSWORD)
VALUES ('AliALiAli', 'Ali', 'Varzandeh', aes_encrypt('007','KEY1234'));






INSERT INTO BASKET (USER_ID, BRAND_NAME ,CATEGORY, SIZE, QUANTITY, ITEM_SUBTOTAL)
VALUES (1,'CANADA GOOSE','Hybridge CW Element Jacket', '42', '1', '£3550');