DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS BASKET;
DROP TABLE IF EXISTS USER;

CREATE TABLE PRODUCTS(
   ID   INT              NOT NULL AUTO_INCREMENT,
   NAME VARCHAR (255)     NOT NULL,
   CATEGORY VARCHAR (100)  NOT NULL,
   SIZE VARCHAR (100)    NOT NULL,
   COLOUR varchar (20)   NOT NULL,
   QUANTITY varchar (100) NOT NULL,
   BRAND varchar (100)   NOT NULL,
    UUID varchar (255)   NOT NULL,
   PRIMARY KEY (ID)
   
);

CREATE TABLE USER (
USER_ID  INT  NOT NULL  AUTO_INCREMENT,
USER_NAME  VARCHAR (45) NOT NULL,
FIRST_NAME VARCHAR (45) NOT NULL,
SURNAME    VARCHAR (45) NOT NULL,
PASSWORD   BINARY (64) NOT NULL,
PRIMARY KEY (USER_ID)

);

CREATE TABLE BASKET(
   ID   INT NOT NULL AUTO_INCREMENT,
   USER_ID     INT   ,
   BRAND_NAME  VARCHAR (100)   NOT NULL,
   CATEGORY VARCHAR (100)  NOT NULL,
   SIZE VARCHAR (100)     NOT NULL,
   QUANTITY VARCHAR (255) NOT NULL,
   ITEM_SUBTOTAL  VARCHAR (255)   NOT NULL,
   PRIMARY  KEY (ID) ,
   FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
   
);

INSERT INTO PRODUCTS (NAME,CATEGORY, SIZE, COLOUR, QUANTITY, BRAND, UUID)
VALUES ('Hybridge CW Element Jacket', 'Jacket', '42', 'BLACK', '1', 'CANADA GOOSE', 'bc7d650b-f778-4b8d-8f75-1bc1cd35a0b1');

INSERT INTO PRODUCTS (NAME,CATEGORY, SIZE, COLOUR, QUANTITY, BRAND, UUID)
VALUES ('Hybridge CW Element Jacket', 'Jacket', '46', 'GREEN', '1', 'CANADA GOOSE', 'bc7d650b-f778-4b8d-8f75-1bc1cd35a0b1');




INSERT INTO USER ( USER_NAME, FIRST_NAME, SURNAME, PASSWORD)
VALUES ('Ali007','Ali', 'Varzandeh','007');

INSERT INTO USER ( USER_NAME, FIRST_NAME, SURNAME, PASSWORD)
VALUES ('AliALiAli', 'Ali', 'Varzandeh', aes_encrypt('007','KEY1234'));






INSERT INTO BASKET (USER_ID, BRAND_NAME ,CATEGORY, SIZE, QUANTITY, ITEM_SUBTOTAL)
VALUES (1,'CANADA GOOSE','Hybridge CW Element Jacket', '42', '1', '£3550');























