DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
USER_ID  INT  NOT NULL  AUTO_INCREMENT,
USER_NAME  VARCHAR (45) NOT NULL,
FIRST_NAME VARCHAR (45) NOT NULL,
SURNAME    VARCHAR (45) NOT NULL,
PASSWORD   BINARY (64) NOT NULL,
PRIMARY KEY (USER_ID)

);

INSERT INTO USER ( USER_NAME, FIRST_NAME, SURNAME, PASSWORD)
VALUES ('Ali007','Ali', 'Varzandeh','007');

INSERT INTO USER ( USER_NAME, FIRST_NAME, SURNAME, PASSWORD)
VALUES ('AliALiAli', 'Ali', 'Varzandeh', aes_encrypt('007','KEY1234'));










